
FROM alpine:3

LABEL author="Masrianto"
LABEL company="Masrianto Web Design" website="https://www.masrianto.com/" email="admin@masrianto.com" version="1.0"

RUN mkdir hello
RUN echo  "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"
